[build]
  command = "npm run generate"
  publish = ".output/public"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200